package com.thekeeperofpie.artistalleydatabase.utils_compose

import androidx.compose.material.icons.materialPath
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.unit.dp

object CustomIcons {

    val Browse = ImageVector.Builder(
        name = "Browse",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 960f,
        viewportHeight = 960f
    ).apply {
        materialPath {
            moveTo(120f, 520f)
            verticalLineToRelative(-320f)
            quadToRelative(0f, -33f, 23.5f, -56.5f)
            reflectiveQuadTo(200f, 120f)
            horizontalLineToRelative(240f)
            verticalLineToRelative(400f)
            horizontalLineTo(120f)
            close()
            moveToRelative(240f, -80f)
            close()
            moveToRelative(160f, -320f)
            horizontalLineToRelative(240f)
            quadToRelative(33f, 0f, 56.5f, 23.5f)
            reflectiveQuadTo(840f, 200f)
            verticalLineToRelative(160f)
            horizontalLineTo(520f)
            verticalLineToRelative(-240f)
            close()
            moveToRelative(0f, 720f)
            verticalLineToRelative(-400f)
            horizontalLineToRelative(320f)
            verticalLineToRelative(320f)
            quadToRelative(0f, 33f, -23.5f, 56.5f)
            reflectiveQuadTo(760f, 840f)
            horizontalLineTo(520f)
            close()
            moveTo(120f, 600f)
            horizontalLineToRelative(320f)
            verticalLineToRelative(240f)
            horizontalLineTo(200f)
            quadToRelative(-33f, 0f, -56.5f, -23.5f)
            reflectiveQuadTo(120f, 760f)
            verticalLineToRelative(-160f)
            close()
            moveToRelative(240f, 80f)
            close()
            moveToRelative(240f, -400f)
            close()
            moveToRelative(0f, 240f)
            close()
            moveToRelative(-400f, -80f)
            horizontalLineToRelative(160f)
            verticalLineToRelative(-240f)
            horizontalLineTo(200f)
            verticalLineToRelative(240f)
            close()
            moveToRelative(400f, -160f)
            horizontalLineToRelative(160f)
            verticalLineToRelative(-80f)
            horizontalLineTo(600f)
            verticalLineToRelative(80f)
            close()
            moveToRelative(0f, 240f)
            verticalLineToRelative(240f)
            horizontalLineToRelative(160f)
            verticalLineToRelative(-240f)
            horizontalLineTo(600f)
            close()
            moveTo(200f, 680f)
            verticalLineToRelative(80f)
            horizontalLineToRelative(160f)
            verticalLineToRelative(-80f)
            horizontalLineTo(200f)
            close()
        }
    }.build()

    val GalleryThumbnail = ImageVector.Builder(
        name = "GalleryThumbnail",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 960f,
        viewportHeight = 960f
    ).apply {
        materialPath {
            moveTo(120f, 760f)
            quadToRelative(-33f, 0f, -56.5f, -23.5f)
            reflectiveQuadTo(40f, 680f)
            verticalLineToRelative(-400f)
            quadToRelative(0f, -33f, 23.5f, -56.5f)
            reflectiveQuadTo(120f, 200f)
            horizontalLineToRelative(400f)
            quadToRelative(33f, 0f, 56.5f, 23.5f)
            reflectiveQuadTo(600f, 280f)
            verticalLineToRelative(400f)
            quadToRelative(0f, 33f, -23.5f, 56.5f)
            reflectiveQuadTo(520f, 760f)
            horizontalLineTo(120f)
            close()
            moveToRelative(600f, -320f)
            quadToRelative(-17f, 0f, -28.5f, -11.5f)
            reflectiveQuadTo(680f, 400f)
            verticalLineToRelative(-160f)
            quadToRelative(0f, -17f, 11.5f, -28.5f)
            reflectiveQuadTo(720f, 200f)
            horizontalLineToRelative(160f)
            quadToRelative(17f, 0f, 28.5f, 11.5f)
            reflectiveQuadTo(920f, 240f)
            verticalLineToRelative(160f)
            quadToRelative(0f, 17f, -11.5f, 28.5f)
            reflectiveQuadTo(880f, 440f)
            horizontalLineTo(720f)
            close()
            moveToRelative(40f, -80f)
            horizontalLineToRelative(80f)
            verticalLineToRelative(-80f)
            horizontalLineToRelative(-80f)
            verticalLineToRelative(80f)
            close()
            moveTo(120f, 680f)
            horizontalLineToRelative(400f)
            verticalLineToRelative(-400f)
            horizontalLineTo(120f)
            verticalLineToRelative(400f)
            close()
            moveToRelative(40f, -80f)
            horizontalLineToRelative(320f)
            lineTo(375f, 460f)
            lineToRelative(-75f, 100f)
            lineToRelative(-55f, -73f)
            lineToRelative(-85f, 113f)
            close()
            moveToRelative(560f, 160f)
            quadToRelative(-17f, 0f, -28.5f, -11.5f)
            reflectiveQuadTo(680f, 720f)
            verticalLineToRelative(-160f)
            quadToRelative(0f, -17f, 11.5f, -28.5f)
            reflectiveQuadTo(720f, 520f)
            horizontalLineToRelative(160f)
            quadToRelative(17f, 0f, 28.5f, 11.5f)
            reflectiveQuadTo(920f, 560f)
            verticalLineToRelative(160f)
            quadToRelative(0f, 17f, -11.5f, 28.5f)
            reflectiveQuadTo(880f, 760f)
            horizontalLineTo(720f)
            close()
            moveToRelative(40f, -80f)
            horizontalLineToRelative(80f)
            verticalLineToRelative(-80f)
            horizontalLineToRelative(-80f)
            verticalLineToRelative(80f)
            close()
            moveToRelative(-640f, 0f)
            verticalLineToRelative(-400f)
            verticalLineToRelative(400f)
            close()
            moveToRelative(640f, -320f)
            verticalLineToRelative(-80f)
            verticalLineToRelative(80f)
            close()
            moveToRelative(0f, 320f)
            verticalLineToRelative(-80f)
            verticalLineToRelative(80f)
            close()
        }
    }.build()

    val Package2 = ImageVector.Builder(
        name = "Package2",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 960f,
        viewportHeight = 960f
    ).apply {
        materialPath {
            moveTo(440f, 777f)
            verticalLineToRelative(-274f)
            lineTo(200f, 364f)
            verticalLineToRelative(274f)
            lineToRelative(240f, 139f)
            close()
            moveToRelative(80f, 0f)
            lineToRelative(240f, -139f)
            verticalLineToRelative(-274f)
            lineTo(520f, 503f)
            verticalLineToRelative(274f)
            close()
            moveToRelative(-80f, 92f)
            lineTo(160f, 708f)
            quadToRelative(-19f, -11f, -29.5f, -29f)
            reflectiveQuadTo(120f, 639f)
            verticalLineToRelative(-318f)
            quadToRelative(0f, -22f, 10.5f, -40f)
            reflectiveQuadToRelative(29.5f, -29f)
            lineToRelative(280f, -161f)
            quadToRelative(19f, -11f, 40f, -11f)
            reflectiveQuadToRelative(40f, 11f)
            lineToRelative(280f, 161f)
            quadToRelative(19f, 11f, 29.5f, 29f)
            reflectiveQuadToRelative(10.5f, 40f)
            verticalLineToRelative(318f)
            quadToRelative(0f, 22f, -10.5f, 40f)
            reflectiveQuadTo(800f, 708f)
            lineTo(520f, 869f)
            quadToRelative(-19f, 11f, -40f, 11f)
            reflectiveQuadToRelative(-40f, -11f)
            close()
            moveToRelative(200f, -528f)
            lineToRelative(77f, -44f)
            lineToRelative(-237f, -137f)
            lineToRelative(-78f, 45f)
            lineToRelative(238f, 136f)
            close()
            moveToRelative(-160f, 93f)
            lineToRelative(78f, -45f)
            lineToRelative(-237f, -137f)
            lineToRelative(-78f, 45f)
            lineToRelative(237f, 137f)
            close()
        }
    }.build()

    val ServerPerson = ImageVector.Builder(
        name = "ServerPerson",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 960f,
        viewportHeight = 960f
    ).apply {
        materialPath {
            moveTo(240f, 880f)
            quadToRelative(-33f, 0f, -56.5f, -23.5f)
            reflectiveQuadTo(160f, 800f)
            verticalLineToRelative(-640f)
            quadToRelative(0f, -33f, 23.5f, -56.5f)
            reflectiveQuadTo(240f, 80f)
            horizontalLineToRelative(480f)
            quadToRelative(33f, 0f, 56.5f, 23.5f)
            reflectiveQuadTo(800f, 160f)
            verticalLineToRelative(640f)
            quadToRelative(0f, 33f, -23.5f, 56.5f)
            reflectiveQuadTo(720f, 880f)
            horizontalLineTo(600f)
            lineToRelative(-40f, -80f)
            horizontalLineTo(400f)
            lineToRelative(-40f, 80f)
            horizontalLineTo(240f)
            close()
            moveToRelative(0f, -80f)
            horizontalLineToRelative(70f)
            lineToRelative(40f, -80f)
            horizontalLineToRelative(260f)
            lineToRelative(40f, 80f)
            horizontalLineToRelative(70f)
            verticalLineToRelative(-640f)
            horizontalLineTo(240f)
            verticalLineToRelative(640f)
            close()
            moveToRelative(80f, -200f)
            horizontalLineToRelative(320f)
            verticalLineToRelative(-22f)
            quadToRelative(0f, -52f, -50f, -75f)
            reflectiveQuadToRelative(-110f, -23f)
            quadToRelative(-60f, 0f, -110f, 23f)
            reflectiveQuadToRelative(-50f, 75f)
            verticalLineToRelative(22f)
            close()
            moveToRelative(160f, -160f)
            quadToRelative(33f, 0f, 56.5f, -23.5f)
            reflectiveQuadTo(560f, 360f)
            quadToRelative(0f, -33f, -23.5f, -56.5f)
            reflectiveQuadTo(480f, 280f)
            quadToRelative(-33f, 0f, -56.5f, 23.5f)
            reflectiveQuadTo(400f, 360f)
            quadToRelative(0f, 33f, 23.5f, 56.5f)
            reflectiveQuadTo(480f, 440f)
            close()
            moveToRelative(0f, 40f)
            close()
        }
    }.build()

    val TableSign = ImageVector.Builder(
        name = "TableSign",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 960f,
        viewportHeight = 960f
    ).apply {
        materialPath {
            moveTo(280f, 480f)
            horizontalLineToRelative(400f)
            verticalLineToRelative(-80f)
            horizontalLineTo(280f)
            verticalLineToRelative(80f)
            close()
            moveToRelative(0f, -160f)
            horizontalLineToRelative(400f)
            verticalLineToRelative(-80f)
            horizontalLineTo(280f)
            verticalLineToRelative(80f)
            close()
            moveToRelative(200f, 40f)
            close()
            moveToRelative(-40f, 440f)
            verticalLineToRelative(-110f)
            quadToRelative(-18f, -11f, -29f, -29f)
            reflectiveQuadToRelative(-11f, -41f)
            quadToRelative(0f, -33f, 23f, -56.5f)
            reflectiveQuadToRelative(57f, -23.5f)
            quadToRelative(33f, 0f, 56.5f, 23.5f)
            reflectiveQuadTo(560f, 620f)
            quadToRelative(0f, 23f, -11f, 40.5f)
            reflectiveQuadTo(520f, 689f)
            verticalLineToRelative(111f)
            horizontalLineToRelative(160f)
            quadToRelative(33f, 0f, 56.5f, 23.5f)
            reflectiveQuadTo(760f, 880f)
            horizontalLineTo(200f)
            quadToRelative(0f, -33f, 23f, -56.5f)
            reflectiveQuadToRelative(57f, -23.5f)
            horizontalLineToRelative(160f)
            close()
            moveTo(200f, 640f)
            quadToRelative(-33f, 0f, -56.5f, -23.5f)
            reflectiveQuadTo(120f, 560f)
            verticalLineToRelative(-400f)
            quadToRelative(0f, -33f, 23.5f, -56.5f)
            reflectiveQuadTo(200f, 80f)
            horizontalLineToRelative(560f)
            quadToRelative(33f, 0f, 56.5f, 23.5f)
            reflectiveQuadTo(840f, 160f)
            verticalLineToRelative(400f)
            quadToRelative(0f, 33f, -23.5f, 56.5f)
            reflectiveQuadTo(760f, 640f)
            horizontalLineTo(639f)
            quadToRelative(2f, -20f, -0.5f, -40.5f)
            reflectiveQuadTo(628f, 560f)
            horizontalLineToRelative(132f)
            verticalLineToRelative(-400f)
            horizontalLineTo(200f)
            verticalLineToRelative(400f)
            horizontalLineToRelative(131f)
            quadToRelative(-8f, 19f, -10f, 39.5f)
            reflectiveQuadToRelative(0f, 40.5f)
            horizontalLineTo(200f)
            close()
        }
    }.build()

    val TextAd = ImageVector.Builder(
        name = "TextAd",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 960f,
        viewportHeight = 960f
    ).apply {
        materialPath {
            moveTo(200f, 680f)
            horizontalLineToRelative(560f)
            verticalLineToRelative(-80f)
            horizontalLineTo(200f)
            verticalLineToRelative(80f)
            close()
            moveToRelative(0f, -160f)
            horizontalLineToRelative(560f)
            verticalLineToRelative(-80f)
            horizontalLineTo(200f)
            verticalLineToRelative(80f)
            close()
            moveToRelative(0f, -160f)
            horizontalLineToRelative(400f)
            verticalLineToRelative(-80f)
            horizontalLineTo(200f)
            verticalLineToRelative(80f)
            close()
            moveToRelative(-40f, 440f)
            quadToRelative(-33f, 0f, -56.5f, -23.5f)
            reflectiveQuadTo(80f, 720f)
            verticalLineToRelative(-480f)
            quadToRelative(0f, -33f, 23.5f, -56.5f)
            reflectiveQuadTo(160f, 160f)
            horizontalLineToRelative(640f)
            quadToRelative(33f, 0f, 56.5f, 23.5f)
            reflectiveQuadTo(880f, 240f)
            verticalLineToRelative(480f)
            quadToRelative(0f, 33f, -23.5f, 56.5f)
            reflectiveQuadTo(800f, 800f)
            horizontalLineTo(160f)
            close()
            moveToRelative(0f, -80f)
            horizontalLineToRelative(640f)
            verticalLineToRelative(-480f)
            horizontalLineTo(160f)
            verticalLineToRelative(480f)
            close()
            moveToRelative(0f, 0f)
            verticalLineToRelative(-480f)
            verticalLineToRelative(480f)
            close()
        }
    }.build()

    val TvGen = ImageVector.Builder(
        name = "TvGen",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 960f,
        viewportHeight = 960f
    ).apply {
        materialPath {
            moveTo(160f, 840f)
            verticalLineToRelative(-80f)
            quadToRelative(-33f, 0f, -56.5f, -23.5f)
            reflectiveQuadTo(80f, 680f)
            verticalLineToRelative(-440f)
            quadToRelative(0f, -33f, 23.5f, -56.5f)
            reflectiveQuadTo(160f, 160f)
            horizontalLineToRelative(640f)
            quadToRelative(33f, 0f, 56.5f, 23.5f)
            reflectiveQuadTo(880f, 240f)
            verticalLineToRelative(440f)
            quadToRelative(0f, 33f, -23.5f, 56.5f)
            reflectiveQuadTo(800f, 760f)
            verticalLineToRelative(80f)
            horizontalLineToRelative(-40f)
            lineToRelative(-26f, -80f)
            horizontalLineTo(227f)
            lineToRelative(-27f, 80f)
            horizontalLineToRelative(-40f)
            close()
            moveToRelative(0f, -160f)
            horizontalLineToRelative(640f)
            verticalLineToRelative(-440f)
            horizontalLineTo(160f)
            verticalLineToRelative(440f)
            close()
            moveToRelative(320f, -220f)
            close()
        }
    }.build()
}
