package com.thekeeperofpie.artistalleydatabase.alley.app

import com.thekeeperofpie.artistalleydatabase.alley.ArtistAlleyComponent
import com.thekeeperofpie.artistalleydatabase.inject.SingletonScope

@SingletonScope
interface ArtistAlleyAppComponent : ArtistAlleyComponent
