package com.thekeeperofpie.artistalleydatabase.anime.recommendations

interface RecommendationsComponent {
    val animeMediaDetailsRecommendationsViewModelFactoryFactory: AnimeMediaDetailsRecommendationsViewModel.TypedFactory.Factory
    val recommendationsSortFilterViewModelFactory: RecommendationsSortFilterViewModel.Factory
    val recommendationsViewModelFactoryFactory: RecommendationsViewModel.TypedFactory.Factory
}
