package com.thekeeperofpie.artistalleydatabase.anime.characters

import com.thekeeperofpie.artistalleydatabase.anime.characters.details.AnimeCharacterDetailsViewModel
import com.thekeeperofpie.artistalleydatabase.anime.characters.media.CharacterMediaSortFilterViewModel
import com.thekeeperofpie.artistalleydatabase.anime.characters.media.CharacterMediasViewModel

interface CharactersComponent {
    val animeCharacterDetailsViewModelFactoryFactory: AnimeCharacterDetailsViewModel.TypedFactory.Factory
    val animeMediaDetailsCharactersViewModelFactory: AnimeMediaDetailsCharactersViewModel.Factory
    val characterSortFilterViewModelFactory: CharacterSortFilterViewModel.Factory
    val characterMediaSortFilterViewModelFactory: CharacterMediaSortFilterViewModel.Factory
    val characterMediasViewModelFactoryFactory: CharacterMediasViewModel.TypedFactory.Factory
}
