package com.thekeeperofpie.artistalleydatabase.alley.links.logo

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

internal val GameJolt = ImageVector.Builder(
    name = "Game Jolt",
    defaultWidth = 24.dp,
    defaultHeight = 24.dp,
    viewportWidth = 64f,
    viewportHeight = 64f
).apply {
    path(
        fill = SolidColor(Color.Black),
        fillAlpha = 1.0f,
        stroke = SolidColor(Color(0xFF000000)),
        strokeAlpha = 1.0f,
        strokeLineWidth = 1.0f,
        strokeLineCap = StrokeCap.Butt,
        strokeLineJoin = StrokeJoin.Miter,
        strokeLineMiter = 1.0f,
        pathFillType = PathFillType.NonZero
    ) {
        moveTo(16f, 0f)
        horizontalLineToRelative(48f)
        moveTo(16f, 1f)
        horizontalLineToRelative(48f)
        moveTo(16f, 2f)
        horizontalLineToRelative(48f)
        moveTo(16f, 3f)
        horizontalLineToRelative(48f)
        moveTo(16f, 4f)
        horizontalLineToRelative(44f)
        moveTo(16f, 5f)
        horizontalLineToRelative(44f)
        moveTo(16f, 6f)
        horizontalLineToRelative(44f)
        moveTo(16f, 7f)
        horizontalLineToRelative(44f)
        moveTo(12f, 8f)
        horizontalLineToRelative(8f)
        moveTo(48f, 8f)
        horizontalLineToRelative(8f)
        moveTo(12f, 9f)
        horizontalLineToRelative(8f)
        moveTo(48f, 9f)
        horizontalLineToRelative(8f)
        moveTo(12f, 10f)
        horizontalLineToRelative(8f)
        moveTo(48f, 10f)
        horizontalLineToRelative(8f)
        moveTo(12f, 11f)
        horizontalLineToRelative(8f)
        moveTo(48f, 11f)
        horizontalLineToRelative(8f)
        moveTo(12f, 12f)
        horizontalLineToRelative(8f)
        moveTo(44f, 12f)
        horizontalLineToRelative(8f)
        moveTo(12f, 13f)
        horizontalLineToRelative(8f)
        moveTo(44f, 13f)
        horizontalLineToRelative(8f)
        moveTo(12f, 14f)
        horizontalLineToRelative(8f)
        moveTo(44f, 14f)
        horizontalLineToRelative(8f)
        moveTo(12f, 15f)
        horizontalLineToRelative(8f)
        moveTo(44f, 15f)
        horizontalLineToRelative(8f)
        moveTo(8f, 16f)
        horizontalLineToRelative(8f)
        moveTo(40f, 16f)
        horizontalLineToRelative(8f)
        moveTo(8f, 17f)
        horizontalLineToRelative(8f)
        moveTo(40f, 17f)
        horizontalLineToRelative(8f)
        moveTo(8f, 18f)
        horizontalLineToRelative(8f)
        moveTo(40f, 18f)
        horizontalLineToRelative(8f)
        moveTo(8f, 19f)
        horizontalLineToRelative(8f)
        moveTo(40f, 19f)
        horizontalLineToRelative(8f)
        moveTo(8f, 20f)
        horizontalLineToRelative(8f)
        moveTo(36f, 20f)
        horizontalLineToRelative(24f)
        moveTo(8f, 21f)
        horizontalLineToRelative(8f)
        moveTo(36f, 21f)
        horizontalLineToRelative(24f)
        moveTo(8f, 22f)
        horizontalLineToRelative(8f)
        moveTo(36f, 22f)
        horizontalLineToRelative(24f)
        moveTo(8f, 23f)
        horizontalLineToRelative(8f)
        moveTo(36f, 23f)
        horizontalLineToRelative(24f)
        moveTo(4f, 24f)
        horizontalLineToRelative(8f)
        moveTo(16f, 24f)
        horizontalLineToRelative(4f)
        moveTo(24f, 24f)
        horizontalLineToRelative(4f)
        moveTo(32f, 24f)
        horizontalLineToRelative(24f)
        moveTo(4f, 25f)
        horizontalLineToRelative(8f)
        moveTo(16f, 25f)
        horizontalLineToRelative(4f)
        moveTo(24f, 25f)
        horizontalLineToRelative(4f)
        moveTo(32f, 25f)
        horizontalLineToRelative(24f)
        moveTo(4f, 26f)
        horizontalLineToRelative(8f)
        moveTo(16f, 26f)
        horizontalLineToRelative(4f)
        moveTo(24f, 26f)
        horizontalLineToRelative(4f)
        moveTo(32f, 26f)
        horizontalLineToRelative(24f)
        moveTo(4f, 27f)
        horizontalLineToRelative(8f)
        moveTo(16f, 27f)
        horizontalLineToRelative(4f)
        moveTo(24f, 27f)
        horizontalLineToRelative(4f)
        moveTo(32f, 27f)
        horizontalLineToRelative(24f)
        moveTo(4f, 28f)
        horizontalLineToRelative(12f)
        moveTo(20f, 28f)
        horizontalLineToRelative(4f)
        moveTo(28f, 28f)
        horizontalLineToRelative(4f)
        moveTo(36f, 28f)
        horizontalLineToRelative(4f)
        moveTo(44f, 28f)
        horizontalLineToRelative(8f)
        moveTo(4f, 29f)
        horizontalLineToRelative(12f)
        moveTo(20f, 29f)
        horizontalLineToRelative(4f)
        moveTo(28f, 29f)
        horizontalLineToRelative(4f)
        moveTo(36f, 29f)
        horizontalLineToRelative(4f)
        moveTo(44f, 29f)
        horizontalLineToRelative(8f)
        moveTo(4f, 30f)
        horizontalLineToRelative(12f)
        moveTo(20f, 30f)
        horizontalLineToRelative(4f)
        moveTo(28f, 30f)
        horizontalLineToRelative(4f)
        moveTo(36f, 30f)
        horizontalLineToRelative(4f)
        moveTo(44f, 30f)
        horizontalLineToRelative(8f)
        moveTo(4f, 31f)
        horizontalLineToRelative(12f)
        moveTo(20f, 31f)
        horizontalLineToRelative(4f)
        moveTo(28f, 31f)
        horizontalLineToRelative(4f)
        moveTo(36f, 31f)
        horizontalLineToRelative(4f)
        moveTo(44f, 31f)
        horizontalLineToRelative(8f)
        moveTo(0f, 32f)
        horizontalLineToRelative(48f)
        moveTo(0f, 33f)
        horizontalLineToRelative(48f)
        moveTo(0f, 34f)
        horizontalLineToRelative(48f)
        moveTo(0f, 35f)
        horizontalLineToRelative(48f)
        moveTo(0f, 36f)
        horizontalLineToRelative(44f)
        moveTo(0f, 37f)
        horizontalLineToRelative(44f)
        moveTo(0f, 38f)
        horizontalLineToRelative(44f)
        moveTo(0f, 39f)
        horizontalLineToRelative(44f)
        moveTo(24f, 40f)
        horizontalLineToRelative(16f)
        moveTo(24f, 41f)
        horizontalLineToRelative(16f)
        moveTo(24f, 42f)
        horizontalLineToRelative(16f)
        moveTo(24f, 43f)
        horizontalLineToRelative(16f)
        moveTo(24f, 44f)
        horizontalLineToRelative(12f)
        moveTo(24f, 45f)
        horizontalLineToRelative(12f)
        moveTo(24f, 46f)
        horizontalLineToRelative(12f)
        moveTo(24f, 47f)
        horizontalLineToRelative(12f)
        moveTo(20f, 48f)
        horizontalLineToRelative(12f)
        moveTo(20f, 49f)
        horizontalLineToRelative(12f)
        moveTo(20f, 50f)
        horizontalLineToRelative(12f)
        moveTo(20f, 51f)
        horizontalLineToRelative(12f)
        moveTo(20f, 52f)
        horizontalLineToRelative(8f)
        moveTo(20f, 53f)
        horizontalLineToRelative(8f)
        moveTo(20f, 54f)
        horizontalLineToRelative(8f)
        moveTo(20f, 55f)
        horizontalLineToRelative(8f)
        moveTo(16f, 56f)
        horizontalLineToRelative(8f)
        moveTo(16f, 57f)
        horizontalLineToRelative(8f)
        moveTo(16f, 58f)
        horizontalLineToRelative(8f)
        moveTo(16f, 59f)
        horizontalLineToRelative(8f)
        moveTo(16f, 60f)
        horizontalLineToRelative(4f)
        moveTo(16f, 61f)
        horizontalLineToRelative(4f)
        moveTo(16f, 62f)
        horizontalLineToRelative(4f)
        moveTo(16f, 63f)
        horizontalLineToRelative(4f)
    }
}.build()
