/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.thekeeperofpie.artistalleydatabase.json_schema

import org.gradle.testkit.runner.GradleRunner
import org.junit.Rule
import org.junit.rules.TemporaryFolder
import kotlin.test.Test
import kotlin.test.assertTrue

/**
 * A simple functional test for the 'com.thekeeperofpie.artistalleydatabase.json_schema' plugin.
 */
class JsonSchemaPluginFunctionalTest {
    @get:Rule val tempFolder = TemporaryFolder()

    private fun getProjectDir() = tempFolder.root
    private fun getBuildFile() = getProjectDir().resolve("build.gradle")
    private fun getSettingsFile() = getProjectDir().resolve("settings.gradle")

    @Test fun `can run task`() {
        // Setup the test build
        getSettingsFile().writeText("")
        getBuildFile().writeText("""
            plugins {
                id('com.thekeeperofpie.artistalleydatabase.json_schema')
            }
            """
        )

        // Run the build
        val runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withProjectDir(getProjectDir())
        val result = runner.build()

        // Verify the result
        assertTrue(result.output.contains("Hello from plugin 'com.thekeeperofpie.artistalleydatabase.json_schema'"))
    }
}
