package com.thekeeperofpie.artistalleydatabase

import com.thekeeperofpie.artistalleydatabase.animethemes.AnimeThemesComponent
import com.thekeeperofpie.artistalleydatabase.debug.DebugComponent

interface ApplicationVariantComponent : DebugComponent, AnimeThemesComponent
