package com.thekeeperofpie.artistalleydatabase

import com.thekeeperofpie.artistalleydatabase.animethemes.AnimeThemesComponent
import com.thekeeperofpie.artistalleydatabase.debug.DebugComponent
import com.thekeeperofpie.artistalleydatabase.monetization.debug.DebugMonetizationComponent

interface ApplicationVariantComponent : DebugComponent, DebugMonetizationComponent, AnimeThemesComponent
